/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A lightweight representation of a CellValue for JS. */
export interface JsCell {
  type: string
  value?: string
  numberValue?: number
  boolValue?: boolean
}
/** High-performance file format converter: CSV to XLSX. */
export declare function convertCsvToXlsx(inputPath: string, outputPath: string): number
/** High-performance file format converter: XLSX to CSV. */
export declare function convertXlsxToCsv(inputPath: string, outputPath: string): number
/** A lightweight representation of a RowBatch for JS. */
export declare class JsRowBatch {
  get rowCount(): number
  get headers(): Array<string> | null
  getRow(index: number): Array<JsCell> | null
  toJsonObjects(): Array<any>
  toHtmlReport(title: string, darkMode: boolean): string
}
/** JS Class for CSV Streaming Reading. */
export declare class JsCsvReader {
  static open(path: string, batchSize?: number | undefined | null, parallel?: boolean | undefined | null): JsCsvReader
  get headers(): Array<string> | null
  nextBatch(): JsRowBatch | null
  getMemoryUtilization(): number
}
/** JS Class for XLSX Streaming Reading. */
export declare class JsXlsxReader {
  static open(path: string, batchSize?: number | undefined | null, sheetName?: string | undefined | null, password?: string | undefined | null): JsXlsxReader
  get headers(): Array<string> | null
  nextBatch(): JsRowBatch | null
  getMemoryUtilization(): number
}
/** JS Class for ODS Streaming Reading. */
export declare class JsOdsReader {
  static open(path: string, batchSize?: number | undefined | null, sheetName?: string | undefined | null): JsOdsReader
  get headers(): Array<string> | null
  nextBatch(): JsRowBatch | null
  getMemoryUtilization(): number
}
